export const CANNED_MESSAGES = {
  feed: [
    "Nom nom nom, this is delicious!",
    "Yum! My tummy is happy now.",
    "Is there more? That was so good!",
    "I love snacks! Thank you!",
    "Mmm, tastes like sunshine.",
    "A perfect treat, thank you!",
    "I'm feeling much more energetic now!",
    "That hit the spot!",
    "Can we have this every day?",
    "So yummy! I'm ready to play now.",
    "Delicious! You know exactly what I like.",
    "My favorite! Thanks!",
    "Mmm, so tasty!",
    "I'm full and happy!",
    "That was a great snack!"
  ],
  play: [
    "Whee! That was so much fun!",
    "I love playing with you!",
    "Let's do that again!",
    "I'm so happy when we play together.",
    "You're the best playmate!",
    "That was exhilarating!",
    "I'm having a blast!",
    "Yay! Playtime is the best time!",
    "Can we play more?",
    "I'm so excited!",
    "That was awesome!",
    "I love our games!",
    "You make me so happy!",
    "Let's keep playing!",
    "This is so much fun!"
  ],
  sleep: [
    "Goodnight! See you in my dreams.",
    "Time to recharge. Zzz...",
    "I'm sleepy... goodnight!",
    "Sweet dreams!",
    "I'll be back soon, just need a nap.",
    "Zzz... so cozy...",
    "Night night!",
    "Time for some beauty sleep.",
    "I'm drifting off... bye!",
    "See you when I wake up!",
    "Nap time! Zzz...",
    "Goodnight, best friend!",
    "I'm so tired... Zzz...",
    "Sleep tight!",
    "See you in a bit!"
  ],
  clean: [
    "Ah, much better! All clean now.",
    "Thank you for cleaning up!",
    "I feel so fresh!",
    "Yay! A clean home is a happy home.",
    "Thanks for taking care of me!",
    "Everything is sparkling now!",
    "I love a tidy space!",
    "Thank you! You're so thoughtful.",
    "Much more comfortable now.",
    "All clean! Ready to play?",
    "Thanks for the tidy-up!",
    "I feel great now!",
    "So clean! Thank you!",
    "Everything looks so nice!",
    "Thanks for keeping things neat!"
  ]
};
